# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qpC9zshZaBD9RaYieKbUqebXaZQPLejN
"""



import pandas as pd
import numpy as np

"""# READING DATA USING PANDAS

We use pandas read_csv function to read the csv file in pytho and pandas DataFrame method to convert file into the data frame
"""

df = pd.DataFrame(pd.read_csv('/content/train (1).csv'))
df.head()

df.shape

"""# HANDELING THE NULL VALUES"""

df.isnull().sum()

"""**seperating out the columns which have more than 35% of the values mising in the dataset**"""

x = df.isnull().sum()
drop_col = x[x>(35/100 * df.shape[0])]
drop_col

"""**NOTE**: There is no specific number after which you should drop the column. it's just that we decided that on our own according to what we want."""

drop_col.index

df.drop(drop_col.index, axis = 1, inplace = True)
df.isnull().sum()

df.fillna(df.mean(),inplace = True)
df.isnull().sum()

"""Because **Embarked** contains string values, we see the details of that column seperately from others as strings does not have mean and all."""

df['Embarked'].describe()

"""For Embarked attribute, we will fill the Null values with the most frequent value in the column"""

df['Embarked'].fillna('S',inplace = True)

df.isnull().sum()

df.corr()

"""**sibsp**: Number of Siblings/Spouse abroad

**parch**: Number of Parents/Children abroad
"""

df['FamilySize'] = df['SibSp']+df['Parch']
df.drop(['SibSp','Parch'],axis=1, inplace = True)
df.corr()

"""**FamilySize in the ship doesnot have much correlance with survival rate**

Lets's check if we weather the person was alone or not can affect the survival rate
"""

df['Alone'] = [0 if df['FamilySize'][i]>0 else 1 for i in df.index]
df.head()

df.groupby(['Alone'])['Survived'].mean()

"""**If the person is alone he/she has less chance of surviving**

> The reason might be the person who is travelling with his family might be belonging to rich class and might be prioritize over other
"""

df[['Alone','Fare']].corr()

"""So we can see if the person was not alone, the chance th eticket proce is higher is high"""

df['Sex'] = [0 if df['Sex'][i]=='male'else 1 for i in df.index]
df.groupby(['Sex'])['Survived'].mean()

"""it shows,female passengers have more chance of surviving than male ones

it shows women were prioritized over men
"""

df.groupby(['Embarked'])['Survived'].mean()

"""# CONCLUSION

*  Female passengers were prioritized over men.
*   People with high class or rich people have higher survival rate than others . The hierarichy might have been followed while saving the passengers.

*   Passengers travelling with their family have higher survival rate.
*  Passengers who boarded te ship at Cherbourg, survived more in proportion than the others.
"""